package-lock.json, package.json, src/components/common/PlaylistCard.tsx, src/pages/Guide.tsx, tailwind.config.js
1. 프래그먼트 → `div` 변경
- 컴포넌트가 하나의 카드 단위로 묶이도록 div로 감싸 구조를 개선하였습니다.
2. 카드 클릭 시 상세 페이지 이동 기능 추가
- `PlaylistCard` 클릭 시 해당 플레이리스트 상세 페이지로 이동하도록 기능을 추가했습니다.
- 단, 카드 내부의 `PlaylistAction` 버튼들도 개별 클릭 이벤트를 가지므로, 이벤트 버블링을 방지하기 위해 `onClick={(e) => e.stopPropagation()}` 처리하였습니다.
3. 제목 영역 `line-clamp` 적용
- 플레이리스트 제목이 두 줄 이상일 경우 `...`으로 표시되도록 Tailwind의 `line-clamp-2` 유틸리티 클래스를 적용했습니다.
https://github.com/user-attachments/assets/54892f16-6fda-4675-b4fe-65faa85040f7
- `@tailwindcss/line-clamp` 모듈 설치했습니다. 머지 후 npm install만 해주시면 됩니다! 🙌
=> Feat: PlaylistCard 구조 정리 및 상세 페이지 이동 기능 추가

src/types/comment.ts, src/types/playlist.ts, src/types/user.ts, src/types/video.ts
- 함께 설계한 Supabase 스키마 기반 TypeScript 타입을 정의하였습니다.
- uuid와 timestmap type은 모두 `string`이라고 합니다!
=> Feat: Supabase 스키마 기반 TypeScript 타입 정의 추가

src/App.tsx, src/routes/index.tsx
- `src/routes/index.tsx` 파일에 route 관련 코드를 분리하여 `App.tsx`에서 import 하도록 수정하였습니다.
=> Refactor: route 분리

src/components/playlistDetail/Player.tsx, src/hooks/usePlaylistDetail.ts, src/pages/PlaylistDetail.tsx
- id → playlistId로 네이밍 명확화 (usePlaylistDetail, playlistDetail 수정)
- 플레이리스트 설명(description)의 최대 길이 상수를 컴포넌트 상단으로 분리
- 상수명 MAX_LENGTH → MAX_DESCRIPTION_PREVIEW_LENGTH 로 명확하게 수정
=> Refactor: id를 playlistId로 변경하고 description 길이 상수를 상단으로 분리

src/App.tsx, src/components/playlistDetail/Comments.tsx, src/components/playlistDetail/Player.tsx, src/components/playlistDetail/Videos.tsx, src/components/playlistDetail/playlistSkeleton.tsx, src/hooks/usePlaylistDetail.ts, src/pages/Guide.tsx, src/pages/PlaylistDetail.tsx, src/types/comment.ts, src/types/playlist.ts, src/utils/formatData.ts
- 이슈 넘버 #31
- 이슈 넘버 #40
- 이슈 넘버 #64 
- Player, Videos, Comments 컴포넌트를 하나로 모아 PlaylistDetail 페이지 완성하였습니다.
=> Feat: PlaylistDetail 기능 1차 완성

src/pages/PlaylistCreate.tsx, src/routes/index.tsx, tsconfig.app.json, tsconfig.json, vite.config.ts
- 이슈 넘버 #43
- 절대 경로 설정을 했습니다.
- 제 담당 페이지에 적용했을 땐 잘 돌아가는데 한번 테스트 부탁드립니다!
=> Chore: 절대경로 설정

src/App.tsx, src/components/common/PlaylistCard.tsx, src/layout/Header.tsx, src/layout/NavBar.tsx, src/pages/EditProfile.tsx, src/pages/Login.tsx, src/pages/MyPage.tsx, src/pages/Signup.tsx, src/routes/index.tsx, src/services/axios/axiosInstance.ts, src/services/supabase/supabaseClient.ts, src/services/supabase/uploadProfileImage.ts, src/store/useUserStore.ts
- 이슈 넘버 #50 
- 마이페이지
- 플레이리스트 삭제 기능 구현
- 로그아웃 기능 구현
- mypage/:userId로 경로 변경
- 정보수정
- 프로필 이미지 변경 후 적용 (storage)
- 닉네임(중복 확인), 비밀번호, 소개글 변경 후 적용
- 공통
- export default 방식으로 통일
https://github.com/user-attachments/assets/ab0a75e3-50f9-4dea-9af2-847b4bc4b563
https://github.com/user-attachments/assets/4160a3c5-7cfb-49e1-824a-f4f2d4f09aad
=> Feat: 마이페이지, 정보수정 기능 구현

src/components/myPage/DropDownMenu.tsx, src/pages/MyPage.tsx
- 이슈 넘버 #58 
- 업데이트순으로 변경
- 정렬 필터링 간소화 (업데이트순, 구독순, 좋아요순)
- 드롭다운메뉴 open시 딤처리
- 딤 클릭시 메뉴 close
// 구독순, 좋아요순 필터링은 추후 작업 예정
=> Feat: 업데이트순으로 변경

src/components/playlistDetail/Player.tsx, src/hooks/usePlaylistDetail.ts, src/layout/Header.tsx, src/pages/PlaylistCreate.tsx, src/types/playlist.ts
- 유저 프로필 클릭 시 마이페이지로 이동하기 위한 user_id 정보를 불러오고 타입을 정의했던 부분이 누락되어 다시 pr 올립니다!
=> Fix: user id 패칭을 위한 타입 및 API 응답 구조 수정

src/components/common/TextArea.tsx, src/pages/EditProfile.tsx, src/pages/MyPage.tsx
- 이슈 넘버 #61
- 이슈 넘버 #78 
- 공통
- 마이페이지, 정보수정 react-query로 상태 관리
- 정보수정
- 전부 필수값 제거
- 닉네임은 변경할 경우에만 중복확인
- 수정된 내용 없는 경우 저장 버튼 비활성화
- TextArea
- 불필요한 코드 제거
https://github.com/user-attachments/assets/f9fdda38-a81a-4b9e-9abd-bd84302363e6
=> Feat: 마이페이지, 정보수정 페이지

src/pages/PlaylistCreate.tsx
- [우선] 생성 및 수정 시에 필수 필드 값을 모두 입력하지 않았는데도 버튼이 활성화 되는 이슈 해결
- [우선] 플레이리스트 생성 후 이동되는 플레이리스트 상세 페이지의 id 값이 undefined인 이슈 해결
- [우선] 플레이리스트 수정 시 기존 영상 삭제 버튼을 누르면 실제로 DB에서 삭제가 되어 뒤로가기 시 사용자가 저장 버튼을 누르지 않았음에도 영상이 삭제되었던 이슈 해결 (저장 버튼 클릭 시 기존 영상을 모두 삭제하고 새로운 videoList를 추가하는 로직으로 수정)
- [선택] 플레이리스트 생성 시 공개 여부 기본 값을 true로 수정
=> Refactor: 생성 및 수정 페이지 수정

src/components/common/OverflowMenu.tsx
- 이슈 넘버 #85 
- 페이지 이동시 메뉴 닫히도록 수정
- 메뉴 오픈시 가려짐 현상 수정
https://github.com/user-attachments/assets/12aeeab7-e855-4723-b633-d4cb860c1571
=> Fix: 오버플로우 메뉴 페이지 이동시 닫히도록 수정

src/layout/Header.tsx, src/pages/MyPage.tsx
- 이슈 넘버 #92 
- 다른 유저의 마이페이지 접근시
- 플레이리스트 생성자의 플레이리스트 불러오기
- header 생성자의 닉네임 노출
https://github.com/user-attachments/assets/485e6ab1-9d2d-490c-9e13-a2e6cd8b64ed
=> Feat: 마이페이지 플레이리스트 목록 조건 추가

src/layout/Header.tsx
=> Fix: params 로직 수정

src/pages/Login.tsx, src/pages/Signup.tsx, src/routes/index.tsx
- protectedRoute 설정(비로그인시 로그인 페이지로 이동)
- 로그인 버튼 중복 제거
- 회원가입 시 프로필 이미지 디폴트로 등록
설정 전
설정 후
=> Feat: 로그인 회원가입 수정

src/pages/EditProfile.tsx, src/pages/MyPage.tsx
- 이슈 넘버 #105 
- 프로필 디폴트 이미지 중복 제거
=> Refactor: 프로필 디폴트 이미지 중복 제거

src/pages/EditProfile.tsx
- 이슈 넘버 #88 
- 정보수정 유효성 검사 방식 통일
https://github.com/user-attachments/assets/bc9a367f-bfeb-428d-b926-858687d28180
=> Refactor: 정보수정 유효성 검사 방식 통일

src/pages/PlaylistCreate.tsx
- 제목은 50자, 소개글은 500자로 최대 길이 제한하였습니다.
=> Feat: 플레이리스트 생성 제목, 소개글 최대 길이 제한

src/types/video.ts
- 플레이리스트 생성 시 추가되는 영상의 type이 id가 생성되기 전의 type이라 Video type 내 id 필드를 optional로 수정하였습니다.
=> Refactor: Video id type optional로 수정

src/components/playlistDetail/Comments.tsx
- 이슈 넘버 #113
- 등록 버튼을 누르지 않고, Enter 만으로도 댓글이 등록될 수 있도록 수정했습니다.
=> Feat: 댓글 등록 시 enter 가능

src/layout/Header.tsx
- 이슈 넘버 #115
- 플레이리스트 수정 시 header 내 title이 반영되도록 dependency array에 `playlist.data.title`을 추가하였습니다.
=> Fix: 플레이리스트 수정 시 header 내 title이 반영되도록 dependency 추가

src/components/myPage/DropDownMenu.tsx, src/hooks/useUserPlaylists.ts, src/pages/MyPage.tsx
- 이슈 넘버 #107 
- 마이페이지 구독순, 좋아요순 정렬 추가
https://github.com/user-attachments/assets/5ebcf5f6-ebd6-45bb-91af-621120d77503
=> Feat: 마이페이지 구독순, 좋아요순 정렬 추가

src/pages/EditProfile.tsx, src/pages/MyPage.tsx
- 이슈 넘버 #110 
- 정보수정 닉네임, 비밀번호, 소개글 입력수 제한
- 마이페이지 소개글 폰트 크기 변경
=> Feat: 마이페이지, 정보수정 소개글 수정

src/components/common/Button.tsx, src/components/common/Error.tsx, src/components/common/Input.tsx, src/components/common/OverflowMenu.tsx, src/components/common/SearchBar.tsx, src/components/common/TextArea.tsx, src/components/common/skeleton.tsx, src/components/myPage/DropDownMenu.tsx, src/components/playlistCreate/VideoCard.tsx, src/components/playlistDetail/Comments.tsx, src/hooks/usePlaylistDetail.ts, src/layout/NavBar.tsx, src/pages/EditProfile.tsx, src/pages/ErrorPage.tsx, src/pages/MyPage.tsx, src/services/axios/axiosInstance.ts, src/store/useUserStore.ts
- 이슈 넘버 #119 
- 전체 페이지 절대경로 적용
=> Style: 전체 페이지 절대경로 적용

src/pages/Login.tsx, src/pages/Signup.tsx
- 이슈 넘버 #137 
- 회원가입의 비밀번호 유효성검사, 문구 추가
- 로그인의 기존 알럿 -> 문구로 추가
- 이메일 유효성 추가 (input의 타입을 email로 하면 자동검사를 해서 text타입으로 변경 후 유효성검사 로직을 추가했습니다)
=> Feat: 유효성 문구 통일, 이메일 유효성 검사

src/pages/EditProfile.tsx
=> Feat: 마이페이지 소개글 300자 제한으로 변경

src/App.tsx, src/layout/Header.tsx, src/pages/MyPage.tsx, src/pages/Signup.tsx, src/utils/toast.ts
=> Design: toast 디자인 적용

src/components/playlistDetail/Player.tsx, src/layout/Header.tsx, src/pages/EditProfile.tsx, src/pages/Login.tsx, src/pages/MyPage.tsx, src/pages/Signup.tsx, src/utils/getYoutubeMeta.ts
- 이슈 넘버 #130
- console.log, alert 삭제
- error 처리 방식 통일
=> Refactor: console.log, alert 삭제, 에러 처리 통일화

src/components/common/OverflowMenu.tsx, src/layout/Header.tsx, tests/logout.spec.ts
=> Test: 테스트 코드 형식 통일

src/pages/PlaylistCreate.tsx
- `useEditPlaylistMutation`과 `useCreatePlaylistMutation` 같은 훅들이 조건부로 호출되거나 컴포넌트 함수 내의 다른 함수들 내에서 호출되면 사용할 수 없다고 하여 컴포넌트의 본문에서 직접 호출하도록 수정하였습니다.
=> Fix: 훅 호출 위치 수정

src/pages/PlaylistCreate.tsx
=> Fix: 중복 코드 제거

src/components/myPage/DropDownMenu.tsx, src/constants/dropDownMenuOptions.ts, src/pages/MyPage.tsx
- 이슈 넘버 #176 
- 마이페이지 드롭다운메뉴 옵션명 바뀌지 않는 이슈
https://github.com/user-attachments/assets/cd349619-999a-4924-9009-19d4d61c38ac
=> Fix: 마이페이지 드롭다운메뉴 옵션명 바뀌지 않는 이슈

src/components/common/ModalDelete.tsx, src/components/common/PlaylistCard.tsx, src/layout/Header.tsx
- 이슈 넘버 #
- 플레이리스트 삭제 모달을 구현했습니다.
=> Feat: 삭제 모달 구현

src/hooks/queries/useUserPlaylistsQuery.ts
=> Fix: 플레이리스트 조회 API 복구
